name: Update README.md

on:
  push:
    paths:
      - '**.md'
      - '!README.md'
    branches:
      - main

jobs:
  update_readme:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
    - name: Determine deleted files
      id: get_deleted_files
      run: |
        DELETED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | tr '\n' ' ')
        echo "DELETED_FILES=$DELETED_FILES" >> $GITHUB_ENV
    - run: npm install @actions/core @actions/github fs
    - name: Run script
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        DELETED_FILES: ${{ env.DELETED_FILES }}
      run: node update_readme.js
