name: Update README.md

on:
  push:
    paths:
      - '**.md'
      - '!README.md'
    branches:
      - main
  delete:
    branches:
      - main
    paths:
      - '**.md'
      - '!README.md'

jobs:
  update_readme:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
    - run: npm install @actions/core @actions/github fs
    - name: Run script
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: node update_readme.js
