name: Update README

on:
  push:
    paths:
      - '**.md'
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Set up environment variable for repository name
      run: echo "REPO_NAME=${{ github.repository }}" >> $GITHUB_ENV
    - name: Install dependencies
      run: pip install PyGithub
    - name: Update README
      run: python update_readme.py
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README.md" || exit 0
          git push
