name: Update README
on:
  push:
    branches:
      - main
    paths:
      - '**.md'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Run script
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
        CHANGED_FILES: ${{ github.event.head_commit.modified }}
      run: python update_readme.py "${{ github.event.head_commit.modified }}" 
    - name: Commit and push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "Automatically update README.md"
        git push origin main
