name: Update README

on:
  push:
    paths:
      - '**.md'
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Run Script
      run: node update-readme.js
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
