name: Update README
on:
  push:
    branches:
      - main
    paths:
      - '**.md'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Get changed files
      id: getfile
      run: |
        echo "Changed files:"
        changed_files=$(git diff --name-only HEAD~1 HEAD)
        echo $changed_files
        echo "CHANGED_FILES=$changed_files" >> $GITHUB_ENV
    - name: Run script
      run: python update_readme.py $CHANGED_FILES
    - name: Commit and push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "Automatically update README.md"
        git push origin main
