name: Update README

on:
  push:
    paths:
      - '**.md'
      - '!README.md'
    branches:
      - main
      
jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - name: Install Octokit
      run: npm install @octokit/rest

    - name: Update README.md
      run: node .github/scripts/update_readme.js
