name: Update README
on:
  pull_request:
    types:
      - closed
    paths:
      - '**.md'
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Run script
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: python update_readme.py ${{ github.event.pull_request.merged }} "${{ github.event.pull_request.title }}"
    - name: Commit and push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "Automatically update README.md"
        git push origin main
