name: Update README

on:
  push:
    branches:
      - main
    paths:
      - '**.md'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Run update_readme.py
      run: python update_readme.py

    - name: Commit and push if README.md changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        if git diff --cached --exit-code; then
          echo "No changes in README.md"
        else
          git commit -m "Update README.md"
          git push
        fi
